name: Merge Rules

on:
  schedule:
    - cron: '0 23 * * *' # 每天早上7点触发
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create *.conf
        run: |
          touch china.conf
          touch apple.china.conf
          touch google.china.conf

      - name: Merge rules
        run: |
          curl -L https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf >> china.conf
          curl -L https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf >> apple.china.conf
          curl -L https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf >> google.china.conf

      - name: Process *.conf
        run: |
          sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' china.conf | grep -Ev -e '^#' -e '^$$' > china.conf
          sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' apple.china.conf | grep -Ev -e '^#' -e '^$$' > apple.china.conf
          sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' google.china.conf | grep -Ev -e '^#' -e '^$$' > google.china.conf 
          
      - name: Commit and push changes
        uses: fregante/setup-git-user@v2
      - run: |
          git init
          git checkout -b release
          git add china.conf apple.china.conf google.china.conf
          git commit -m "Merge rules"
          git push -f -u origin release
